---
title: "Автоматизация"
author: "Кирилл Мухин"
date: "17 11 2020"
output:
  html_document:
    code_folding: show
    highlight: tango
    number_sections: yes
    theme: united
    toc: yes
---

```{r message = F, warning = F}
library(dplyr)
library(readxl)
library(Rutils)
library(tibble)
library(openxlsx)

df2 = read_excel("C:/Users/User/Desktop/Table2_All_Lines.xlsx")
df3 = read_excel("C:/Users/User/Desktop/Table3_All_Lines_Grammar_New.xlsx")
```

# Количество ударных иктов

```{r}
ictus_n = data.frame(ictus_num = c("Ictus1","Ictus2","Ictus3","Ictus4"),
                   non_null = c(nrow(df2 %>% filter(Ictus1 != "0")),
                                nrow(df2 %>% filter(Ictus2 != "0")),
                                nrow(df2 %>% filter(Ictus3 != "0")),
                                nrow(df2 %>% filter(Ictus4 != "0")))) %>% 
                   mutate(props = non_null / nrow(df2))

ictus_full = data.frame(total_non_null = sum(ictus_n$non_null)) %>%
  mutate(props = total_non_null / (nrow(df2) * 4))

ictus_n
ictus_full

write.xlsx(ictus_n, "ictus_n.xlsx")
write.xlsx(ictus_full, "ictus_full.xlsx")
```

# Частотность форм четырехстопного ямба

```{r}
rhythm_form = data.frame(group_proportions(df2, RhythmForm))
rhythm_form

write.xlsx(rhythm_form, "rhythm_form.xlsx")
```

# Частотность форм четырехстопного ямба по номерам строф

```{r}
nos = data.frame(group_proportions(df2, NoS, RhythmForm))
nos

write.xlsx(nos, "nos.xlsx")
```

# Частотность частей речи на каждом икте

```{r message = F}
dfi = dplyr::select(df3, Ictus1, Ictus2, Ictus3, Ictus4)
ictus_pos = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  ictus_pos = rbind(ictus_pos, data.frame(Ictus = i, group_proportions(dfi, dfi[,i]) %>%
                                            rename(part_of_speech = 1)))
}

remove(dfi)

ictus_total = ictus_pos[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  group_by(part_of_speech) %>%
  summarise(total = sum(n))

ictus_pos = ictus_pos[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  full_join(ictus_total, by = c("part_of_speech")) %>%
  mutate(props = n / total)

ictus_pos = ictus_pos[,c(1,2,3,5,4)] %>% filter(part_of_speech != "0")
ictus_pos

write.xlsx(ictus_pos, "ictus_pos.xlsx")
```

# Частотность частей речи по ритмическим формам (проценты по всем ритмическим формам)

```{r}
# первая ритмическая форма

d1 = df3 %>% filter(RhythmForm == 1) %>% dplyr::select(Ictus1, Ictus2, Ictus3, Ictus4)
rform_pos1 = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  rform_pos1 = rbind(rform_pos1, data.frame(Ictus = i, group_proportions(d1, d1[,i]) %>%
                                              rename(part_of_speech = 1)))
}

remove(d1)

rform_pos1 = rform_pos1[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  left_join(ictus_total, by = c("part_of_speech")) %>%
  mutate(props = n / total)

# вторая ритмическая форма

d2 = df3 %>% filter(RhythmForm == 2) %>% dplyr::select(Ictus1, Ictus2, Ictus3, Ictus4)
rform_pos2 = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  rform_pos2 = rbind(rform_pos2, data.frame(Ictus = i, group_proportions(d2, d2[,i]) %>%
                                              rename(part_of_speech = 1)))
}

remove(d2)

rform_pos2 = rform_pos2[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  left_join(ictus_total, by = c("part_of_speech")) %>%
  mutate(props = n / total)

# третья ритмическая форма

d3 = df3 %>% filter(RhythmForm == 3) %>% dplyr::select(Ictus1, Ictus2, Ictus3, Ictus4)
rform_pos3 = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  rform_pos3 = rbind(rform_pos3, data.frame(Ictus = i, group_proportions(d3, d3[,i]) %>%
                                              rename(part_of_speech = 1)))
}

remove(d3)

rform_pos3 = rform_pos3[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  left_join(ictus_total, by = c("part_of_speech")) %>%
  mutate(props = n / total)

# четвертая ритмическая форма

d4 = df3 %>% filter(RhythmForm == 4) %>% dplyr::select(Ictus1, Ictus2, Ictus3, Ictus4)
rform_pos4 = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  rform_pos4 = rbind(rform_pos4, data.frame(Ictus = i, group_proportions(d4, d4[,i]) %>%
                                              rename(part_of_speech = 1)))
}

remove(d4)

rform_pos4 = rform_pos4[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  left_join(ictus_total, by = c("part_of_speech")) %>%
  mutate(props = n / total)

# пятая ритмическая форма

d5 = df3 %>% filter(RhythmForm == 5) %>% dplyr::select(Ictus1, Ictus2, Ictus3, Ictus4)
rform_pos5 = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  rform_pos5 = rbind(rform_pos5, data.frame(Ictus = i, group_proportions(d5, d5[,i]) %>%
                                              rename(part_of_speech = 1)))
}

remove(d5)

rform_pos5 = rform_pos5[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  left_join(ictus_total, by = c("part_of_speech")) %>%
  mutate(props = n / total)

# шестая ритмическая форма

d6 = df3 %>% filter(RhythmForm == 6) %>% dplyr::select(Ictus1, Ictus2, Ictus3, Ictus4)
rform_pos6 = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  rform_pos6 = rbind(rform_pos6, data.frame(Ictus = i, group_proportions(d6, d6[,i]) %>%
                                              rename(part_of_speech = 1)))
}

remove(d6)

rform_pos6 = rform_pos6[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  left_join(ictus_total, by = c("part_of_speech")) %>%
  mutate(props = n / total)

# смотрим на результаты

rform_pos1 = data.frame(RhythmForm = 1, rform_pos1)
rform_pos2 = data.frame(RhythmForm = 2, rform_pos2)
rform_pos3 = data.frame(RhythmForm = 3, rform_pos3)
rform_pos4 = data.frame(RhythmForm = 4, rform_pos4)
rform_pos5 = data.frame(RhythmForm = 5, rform_pos5)
rform_pos6 = data.frame(RhythmForm = 6, rform_pos6)

rform_pos = rbind(rform_pos1, rform_pos2, rform_pos3, rform_pos4, rform_pos5, rform_pos6) %>% filter(part_of_speech != "0")

rform_pos

write.xlsx(rform_pos, "rform_pos.xlsx")
```

# Частотность частей речи по ритмическим формам (проценты внутри ритмических форм)

```{r message = F}
# первая ритмическая форма

d1 = df3 %>% filter(RhythmForm == 1) %>% dplyr::select(Ictus1, Ictus2, Ictus3, Ictus4)
rform_pos1 = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  rform_pos1 = rbind(rform_pos1, data.frame(Ictus = i, group_proportions(d1, d1[,i]) %>%
                                              rename(part_of_speech = 1)))
}

remove(d1)

rform_total1 = rform_pos1[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  group_by(part_of_speech) %>%
  summarise(total = sum(n))

rform_pos1 = rform_pos1[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  full_join(rform_total1, by = c("part_of_speech")) %>%
  mutate(props = n / total)

# вторая ритмическая форма

d2 = df3 %>% filter(RhythmForm == 2) %>% dplyr::select(Ictus1, Ictus2, Ictus3, Ictus4)
rform_pos2 = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  rform_pos2 = rbind(rform_pos2, data.frame(Ictus = i, group_proportions(d2, d2[,i]) %>%
                                              rename(part_of_speech = 1)))
}

remove(d2)

rform_total2 = rform_pos2[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  group_by(part_of_speech) %>%
  summarise(total = sum(n))

rform_pos2 = rform_pos2[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  full_join(rform_total2, by = c("part_of_speech")) %>%
  mutate(props = n / total)

# третья ритмическая форма

d3 = df3 %>% filter(RhythmForm == 3) %>% dplyr::select(Ictus1, Ictus2, Ictus3, Ictus4)
rform_pos3 = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  rform_pos3 = rbind(rform_pos3, data.frame(Ictus = i, group_proportions(d3, d3[,i]) %>%
                                              rename(part_of_speech = 1)))
}

remove(d3)

rform_total3 = rform_pos3[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  group_by(part_of_speech) %>%
  summarise(total = sum(n))

rform_pos3 = rform_pos3[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  full_join(rform_total3, by = c("part_of_speech")) %>%
  mutate(props = n / total)

# четвертая ритмическая форма

d4 = df3 %>% filter(RhythmForm == 4) %>% dplyr::select(Ictus1, Ictus2, Ictus3, Ictus4)
rform_pos4 = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  rform_pos4 = rbind(rform_pos4, data.frame(Ictus = i, group_proportions(d4, d4[,i]) %>%
                                              rename(part_of_speech = 1)))
}

remove(d4)

rform_total4 = rform_pos4[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  group_by(part_of_speech) %>%
  summarise(total = sum(n))

rform_pos4 = rform_pos4[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  full_join(rform_total4, by = c("part_of_speech")) %>%
  mutate(props = n / total)

# пятая ритмическая форма

d5 = df3 %>% filter(RhythmForm == 5) %>% dplyr::select(Ictus1, Ictus2, Ictus3, Ictus4)
rform_pos5 = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  rform_pos5 = rbind(rform_pos5, data.frame(Ictus = i, group_proportions(d5, d5[,i]) %>%
                                              rename(part_of_speech = 1)))
}

remove(d5)

rform_total5 = rform_pos5[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  group_by(part_of_speech) %>%
  summarise(total = sum(n))

rform_pos5 = rform_pos5[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  full_join(rform_total5, by = c("part_of_speech")) %>%
  mutate(props = n / total)

# шестая ритмическая форма

d6 = df3 %>% filter(RhythmForm == 6) %>% dplyr::select(Ictus1, Ictus2, Ictus3, Ictus4)
rform_pos6 = data.frame(Ictus = integer(), part_of_speech = character(), n = integer(), props = double())

for(i in 1:4){
  rform_pos6 = rbind(rform_pos6, data.frame(Ictus = i, group_proportions(d6, d6[,i]) %>%
                                              rename(part_of_speech = 1)))
}

remove(d6)

rform_total6 = rform_pos6[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  group_by(part_of_speech) %>%
  summarise(total = sum(n))

rform_pos6 = rform_pos6[,c(2,1,3,4)] %>%
  arrange(part_of_speech) %>%
  full_join(rform_total6, by = c("part_of_speech")) %>%
  mutate(props = n / total)

# смотрим на результаты

rform_pos1 = data.frame(RhythmForm = 1, rform_pos1)
rform_pos2 = data.frame(RhythmForm = 2, rform_pos2)
rform_pos3 = data.frame(RhythmForm = 3, rform_pos3)
rform_pos4 = data.frame(RhythmForm = 4, rform_pos4)
rform_pos5 = data.frame(RhythmForm = 5, rform_pos5)
rform_pos6 = data.frame(RhythmForm = 6, rform_pos6)

rform_pos_v2 = rbind(rform_pos1, rform_pos2, rform_pos3, rform_pos4, rform_pos5, rform_pos6) %>% filter(part_of_speech != "0")

rform_pos_v2

write.xlsx(rform_pos_v2, "rform_pos_v2.xlsx")
```

# Частотность частей речи

```{r}
pos_freq = data.frame(df3 %>%
                        count(Ictus1) %>%
                        rename(part_of_speech = Ictus1) %>%
                        full_join(df3 %>%
                                    count(Ictus2) %>%
                                    rename(part_of_speech = Ictus2), by = "part_of_speech") %>%
                        full_join(df3 %>%
                                    count(Ictus3) %>%
                                    rename(part_of_speech = Ictus3), by = "part_of_speech") %>%
                        full_join(df3 %>%
                                    count(Ictus4) %>%
                                    rename(part_of_speech = Ictus4), by = "part_of_speech") %>%
                        replace(is.na(.), 0) %>%
                        filter(part_of_speech != "0") %>%
                        mutate(n = n.x + n.y + n.x.x + n.y.y, props = n / sum(n)) %>%
                        select(part_of_speech, n, props) %>%
                        arrange(-n))

pos_freq

write.xlsx(pos_freq, "pos_freq.xlsx")
```

